Fixed W-12496812 p1 bug & added empty screen UI
forcedotcom/LWC-Mobile-Samples pull request #23
Opened 2023-02-06 19:16 UTC by ibenitamar

2023-02-06 19:30 UTC, maliroteh-sf requested changes
@ibenitamar This is an open-source repo and as such we should not be referencing any internal work item numbers in PR title or commit messages. Please close this PR and open a new one with appropriate commit message & PR title.

2023-02-06 19:31 UTC, maliroteh-sf commented on RescheduleAppointments/force-app/main/default/lwc/mobileAppointmentBookingResourceAssignment/mobileAppointmentBookingResourceAssignment.html
> +                </template>
fix indentation/formating

2023-02-06 19:32 UTC, maliroteh-sf commented on RescheduleAppointments/force-app/main/default/lwc/mobileAppointmentBookingResourceAssignment/mobileAppointmentBookingResourceAssignment.html
> +                                >
`>` should be at the end of the previous line: `onchange={handleAssignmentMethodChange}>`

2023-02-07 07:23 UTC, closed without merging

2023-02-07 07:54 UTC, ibenitamar commented
@maliroteh-sf done thanks.